apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gtfs-rt-v3-dev

resources:
- ns.yaml
- archiver-channel-vars.yaml
- ../gtfs-rt-archiver-v3-release

patches:
- consumer.patch.yaml
- ticker.patch.yaml

images:
- name: 'gtfs-rt-archiver'
  newName: 'ghcr.io/cal-itp/data-infra/gtfs-rt-archiver'
  newTag: '3.1.6'
