apiVersion: v1
kind: ConfigMap
metadata:
  name: archiver-channel-vars
data:
  AIRFLOW_ENV: cal-itp-data-infra
  CALITP_BUCKET__AIRTABLE: "gs://calitp-airtable"
  CALITP_BUCKET__RT_RAW: "gs://calitp-gtfs-rt-raw"
  HUEY_CONSUMER_WORKERS: "16"
