apiVersion: v2
name: sentry
description: Sentry for Kubernetes
type: application
version: 0.1.0
appVersion: "1.4.2"
dependencies:
  - name: sentry
    version: 27.6.1
    repository: https://sentry-kubernetes.github.io/charts
