apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- '../../manifests/gtfs-rt-archive'

images:
- name: 'gtfs-rt-archive'
  newName: 'us.gcr.io/cal-itp-data-infra/gtfs-rt-archive-test'
  newTag: '1.0-jamesl2'
