name: Build release candidate

on:
  push:
    branches:
      - '*'
    paths:
      - '.holo/config.toml'
      - '.holo/sources/jarvus-cluster-template.toml'
      - '.holo/branches/releases/**'
      - '.github/workflows/service-*'
      - 'ci/**'
      - 'kubernetes/apps/**'
      - 'kubernetes/system/**'


env:
  GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
  BIO_RELEASE: 1.6.372


jobs:
  build-release-candidate:
    runs-on: ubuntu-latest
    steps:

    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: 'Build release candidate branch'
      run: |

        # dependency setup
        curl -LO "https://github.com/biome-sh/biome/releases/download/v1.6.372/bio-$BIO_RELEASE-x86_64-linux.tar.gz"
        tar xzvf "bio-$BIO_RELEASE-x86_64-linux.tar.gz"
        sudo mv bio /usr/local/bin/bio
        sudo bio pkg install --binlink jarvus/hologit

        # environment setup
        [[ ! $(git status --porcelain=v1) ]] || git stash -u
        git config user.name "Github Action $GITHUB_JOB"
        git config user.email "$(whoami)@$(uname -n)"
        remote_name=origin
        candidate_branch=candidates/${GITHUB_REF#refs/heads/}
        candidate_local_ref=refs/heads/$candidate_branch
        candidate_remote_ref=refs/remotes/$remote_name/$candidate_branch

        # branch setup
        if [[ $(git ls-remote "$remote_name" "$candidate_local_ref") ]] && [[ ! $(git show-ref "$candidate_remote_ref") ]]; then
          git fetch "$remote_name" "$candidate_branch"
          if [[ ! $(git show-ref "$candidate_local_ref") ]]; then
            git branch "$candidate_branch" "$remote_name/$candidate_branch"
          fi
        fi

        # build & push
        git holo project release-candidate --commit-to "$candidate_branch" --commit-message "Release candidate: $(git describe --always)"
        git push "$remote_name" "$candidate_branch"
