name: Deploy to a terraform target

on:
  push:
    branches:
      - 'main'
      - 'targets/*'
    paths:
      - 'iac/terraform/*'

jobs:

  deploy:

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
          terraform_wrapper: false

      - name: terraform-deploy
        shell: bash
        env:
          CONTENT_ROOT : ${{ github.workspace     }}/iac
          ENGINE_ROOT  : ${{ github.workspace     }}/iac/.engine
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            export INFRA_TARGET_NAME=prod
          else
            export INFRA_TARGET_NAME=${GITHUB_BASE_BRANCH#targets/}
            if [[ $INFRA_TARGET_NAME == prod ]]; then
              echo "fatal: prod changes must be merged to main branch" >&2
              exit 1
            fi
          fi
          "$ENGINE_ROOT"/bin/terraform-deploy
